// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: rpc/daemon.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseStatus int32

const (
	ResponseStatus_Success ResponseStatus = 0
	ResponseStatus_Error   ResponseStatus = 1
)

// Enum value maps for ResponseStatus.
var (
	ResponseStatus_name = map[int32]string{
		0: "Success",
		1: "Error",
	}
	ResponseStatus_value = map[string]int32{
		"Success": 0,
		"Error":   1,
	}
)

func (x ResponseStatus) Enum() *ResponseStatus {
	p := new(ResponseStatus)
	*p = x
	return p
}

func (x ResponseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_daemon_proto_enumTypes[0].Descriptor()
}

func (ResponseStatus) Type() protoreflect.EnumType {
	return &file_rpc_daemon_proto_enumTypes[0]
}

func (x ResponseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseStatus.Descriptor instead.
func (ResponseStatus) EnumDescriptor() ([]byte, []int) {
	return file_rpc_daemon_proto_rawDescGZIP(), []int{0}
}

type TunnelConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Server        string                 `protobuf:"bytes,3,opt,name=server,proto3" json:"server,omitempty"`
	User          string                 `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	KeyFile       string                 `protobuf:"bytes,5,opt,name=key_file,json=keyFile,proto3" json:"key_file,omitempty"`
	RemoteHost    string                 `protobuf:"bytes,6,opt,name=remote_host,json=remoteHost,proto3" json:"remote_host,omitempty"`
	RemotePort    int32                  `protobuf:"varint,7,opt,name=remote_port,json=remotePort,proto3" json:"remote_port,omitempty"`
	LocalPort     int32                  `protobuf:"varint,8,opt,name=local_port,json=localPort,proto3" json:"local_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelConfig) Reset() {
	*x = TunnelConfig{}
	mi := &file_rpc_daemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelConfig) ProtoMessage() {}

func (x *TunnelConfig) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_daemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelConfig.ProtoReflect.Descriptor instead.
func (*TunnelConfig) Descriptor() ([]byte, []int) {
	return file_rpc_daemon_proto_rawDescGZIP(), []int{0}
}

func (x *TunnelConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TunnelConfig) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TunnelConfig) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *TunnelConfig) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *TunnelConfig) GetKeyFile() string {
	if x != nil {
		return x.KeyFile
	}
	return ""
}

func (x *TunnelConfig) GetRemoteHost() string {
	if x != nil {
		return x.RemoteHost
	}
	return ""
}

func (x *TunnelConfig) GetRemotePort() int32 {
	if x != nil {
		return x.RemotePort
	}
	return 0
}

func (x *TunnelConfig) GetLocalPort() int32 {
	if x != nil {
		return x.LocalPort
	}
	return 0
}

type Machine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Server        string                 `protobuf:"bytes,3,opt,name=server,proto3" json:"server,omitempty"`
	User          string                 `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	KeyFile       string                 `protobuf:"bytes,5,opt,name=key_file,json=keyFile,proto3" json:"key_file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Machine) Reset() {
	*x = Machine{}
	mi := &file_rpc_daemon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Machine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Machine) ProtoMessage() {}

func (x *Machine) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_daemon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Machine.ProtoReflect.Descriptor instead.
func (*Machine) Descriptor() ([]byte, []int) {
	return file_rpc_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *Machine) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Machine) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Machine) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *Machine) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Machine) GetKeyFile() string {
	if x != nil {
		return x.KeyFile
	}
	return ""
}

type TunnelProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	MachineId     string                 `protobuf:"bytes,4,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	RemoteHost    string                 `protobuf:"bytes,5,opt,name=remote_host,json=remoteHost,proto3" json:"remote_host,omitempty"`
	RemotePort    int32                  `protobuf:"varint,6,opt,name=remote_port,json=remotePort,proto3" json:"remote_port,omitempty"`
	LocalPort     int32                  `protobuf:"varint,7,opt,name=local_port,json=localPort,proto3" json:"local_port,omitempty"`
	Machine       *Machine               `protobuf:"bytes,8,opt,name=machine,proto3,oneof" json:"machine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelProfile) Reset() {
	*x = TunnelProfile{}
	mi := &file_rpc_daemon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelProfile) ProtoMessage() {}

func (x *TunnelProfile) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_daemon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelProfile.ProtoReflect.Descriptor instead.
func (*TunnelProfile) Descriptor() ([]byte, []int) {
	return file_rpc_daemon_proto_rawDescGZIP(), []int{2}
}

func (x *TunnelProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TunnelProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TunnelProfile) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TunnelProfile) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *TunnelProfile) GetRemoteHost() string {
	if x != nil {
		return x.RemoteHost
	}
	return ""
}

func (x *TunnelProfile) GetRemotePort() int32 {
	if x != nil {
		return x.RemotePort
	}
	return 0
}

func (x *TunnelProfile) GetLocalPort() int32 {
	if x != nil {
		return x.LocalPort
	}
	return 0
}

func (x *TunnelProfile) GetMachine() *Machine {
	if x != nil {
		return x.Machine
	}
	return nil
}

type ListMachinesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMachinesRequest) Reset() {
	*x = ListMachinesRequest{}
	mi := &file_rpc_daemon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMachinesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMachinesRequest) ProtoMessage() {}

func (x *ListMachinesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_daemon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMachinesRequest.ProtoReflect.Descriptor instead.
func (*ListMachinesRequest) Descriptor() ([]byte, []int) {
	return file_rpc_daemon_proto_rawDescGZIP(), []int{3}
}

type ListMachinesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ResponseStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=daemon.ResponseStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Machines      []*Machine             `protobuf:"bytes,3,rep,name=machines,proto3" json:"machines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMachinesResponse) Reset() {
	*x = ListMachinesResponse{}
	mi := &file_rpc_daemon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMachinesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMachinesResponse) ProtoMessage() {}

func (x *ListMachinesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_daemon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMachinesResponse.ProtoReflect.Descriptor instead.
func (*ListMachinesResponse) Descriptor() ([]byte, []int) {
	return file_rpc_daemon_proto_rawDescGZIP(), []int{4}
}

func (x *ListMachinesResponse) GetStatus() ResponseStatus {
	if x != nil {
		return x.Status
	}
	return ResponseStatus_Success
}

func (x *ListMachinesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListMachinesResponse) GetMachines() []*Machine {
	if x != nil {
		return x.Machines
	}
	return nil
}

type GetMachineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMachineRequest) Reset() {
	*x = GetMachineRequest{}
	mi := &file_rpc_daemon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMachineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMachineRequest) ProtoMessage() {}

func (x *GetMachineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_daemon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMachineRequest.ProtoReflect.Descriptor instead.
func (*GetMachineRequest) Descriptor() ([]byte, []int) {
	return file_rpc_daemon_proto_rawDescGZIP(), []int{5}
}

func (x *GetMachineRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMachineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ResponseStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=daemon.ResponseStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *Machine               `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMachineResponse) Reset() {
	*x = GetMachineResponse{}
	mi := &file_rpc_daemon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMachineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMachineResponse) ProtoMessage() {}

func (x *GetMachineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_daemon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMachineResponse.ProtoReflect.Descriptor instead.
func (*GetMachineResponse) Descriptor() ([]byte, []int) {
	return file_rpc_daemon_proto_rawDescGZIP(), []int{6}
}

func (x *GetMachineResponse) GetStatus() ResponseStatus {
	if x != nil {
		return x.Status
	}
	return ResponseStatus_Success
}

func (x *GetMachineResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetMachineResponse) GetData() *Machine {
	if x != nil {
		return x.Data
	}
	return nil
}

type MachineMutationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          *Machine               `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineMutationRequest) Reset() {
	*x = MachineMutationRequest{}
	mi := &file_rpc_daemon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineMutationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineMutationRequest) ProtoMessage() {}

func (x *MachineMutationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_daemon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineMutationRequest.ProtoReflect.Descriptor instead.
func (*MachineMutationRequest) Descriptor() ([]byte, []int) {
	return file_rpc_daemon_proto_rawDescGZIP(), []int{7}
}

func (x *MachineMutationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MachineMutationRequest) GetData() *Machine {
	if x != nil {
		return x.Data
	}
	return nil
}

type MachineMutationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ResponseStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=daemon.ResponseStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *Machine               `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineMutationResponse) Reset() {
	*x = MachineMutationResponse{}
	mi := &file_rpc_daemon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineMutationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineMutationResponse) ProtoMessage() {}

func (x *MachineMutationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_daemon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineMutationResponse.ProtoReflect.Descriptor instead.
func (*MachineMutationResponse) Descriptor() ([]byte, []int) {
	return file_rpc_daemon_proto_rawDescGZIP(), []int{8}
}

func (x *MachineMutationResponse) GetStatus() ResponseStatus {
	if x != nil {
		return x.Status
	}
	return ResponseStatus_Success
}

func (x *MachineMutationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MachineMutationResponse) GetData() *Machine {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteMachineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMachineRequest) Reset() {
	*x = DeleteMachineRequest{}
	mi := &file_rpc_daemon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMachineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMachineRequest) ProtoMessage() {}

func (x *DeleteMachineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_daemon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMachineRequest.ProtoReflect.Descriptor instead.
func (*DeleteMachineRequest) Descriptor() ([]byte, []int) {
	return file_rpc_daemon_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteMachineRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListTunnelProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTunnelProfilesRequest) Reset() {
	*x = ListTunnelProfilesRequest{}
	mi := &file_rpc_daemon_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTunnelProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTunnelProfilesRequest) ProtoMessage() {}

func (x *ListTunnelProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_daemon_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTunnelProfilesRequest.ProtoReflect.Descriptor instead.
func (*ListTunnelProfilesRequest) Descriptor() ([]byte, []int) {
	return file_rpc_daemon_proto_rawDescGZIP(), []int{10}
}

type ListTunnelProfilesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         ResponseStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=daemon.ResponseStatus" json:"status,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TunnelProfiles []*TunnelProfile       `protobuf:"bytes,3,rep,name=tunnel_profiles,json=tunnelProfiles,proto3" json:"tunnel_profiles,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListTunnelProfilesResponse) Reset() {
	*x = ListTunnelProfilesResponse{}
	mi := &file_rpc_daemon_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTunnelProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTunnelProfilesResponse) ProtoMessage() {}

func (x *ListTunnelProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_daemon_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTunnelProfilesResponse.ProtoReflect.Descriptor instead.
func (*ListTunnelProfilesResponse) Descriptor() ([]byte, []int) {
	return file_rpc_daemon_proto_rawDescGZIP(), []int{11}
}

func (x *ListTunnelProfilesResponse) GetStatus() ResponseStatus {
	if x != nil {
		return x.Status
	}
	return ResponseStatus_Success
}

func (x *ListTunnelProfilesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListTunnelProfilesResponse) GetTunnelProfiles() []*TunnelProfile {
	if x != nil {
		return x.TunnelProfiles
	}
	return nil
}

type GetTunnelProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTunnelProfileRequest) Reset() {
	*x = GetTunnelProfileRequest{}
	mi := &file_rpc_daemon_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTunnelProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTunnelProfileRequest) ProtoMessage() {}

func (x *GetTunnelProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_daemon_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTunnelProfileRequest.ProtoReflect.Descriptor instead.
func (*GetTunnelProfileRequest) Descriptor() ([]byte, []int) {
	return file_rpc_daemon_proto_rawDescGZIP(), []int{12}
}

func (x *GetTunnelProfileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTunnelProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ResponseStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=daemon.ResponseStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *TunnelProfile         `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTunnelProfileResponse) Reset() {
	*x = GetTunnelProfileResponse{}
	mi := &file_rpc_daemon_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTunnelProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTunnelProfileResponse) ProtoMessage() {}

func (x *GetTunnelProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_daemon_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTunnelProfileResponse.ProtoReflect.Descriptor instead.
func (*GetTunnelProfileResponse) Descriptor() ([]byte, []int) {
	return file_rpc_daemon_proto_rawDescGZIP(), []int{13}
}

func (x *GetTunnelProfileResponse) GetStatus() ResponseStatus {
	if x != nil {
		return x.Status
	}
	return ResponseStatus_Success
}

func (x *GetTunnelProfileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetTunnelProfileResponse) GetData() *TunnelProfile {
	if x != nil {
		return x.Data
	}
	return nil
}

type TunnelProfileMutationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          *TunnelProfile         `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelProfileMutationRequest) Reset() {
	*x = TunnelProfileMutationRequest{}
	mi := &file_rpc_daemon_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelProfileMutationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelProfileMutationRequest) ProtoMessage() {}

func (x *TunnelProfileMutationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_daemon_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelProfileMutationRequest.ProtoReflect.Descriptor instead.
func (*TunnelProfileMutationRequest) Descriptor() ([]byte, []int) {
	return file_rpc_daemon_proto_rawDescGZIP(), []int{14}
}

func (x *TunnelProfileMutationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TunnelProfileMutationRequest) GetData() *TunnelProfile {
	if x != nil {
		return x.Data
	}
	return nil
}

type TunnelProfileMutationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ResponseStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=daemon.ResponseStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *TunnelProfile         `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelProfileMutationResponse) Reset() {
	*x = TunnelProfileMutationResponse{}
	mi := &file_rpc_daemon_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelProfileMutationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelProfileMutationResponse) ProtoMessage() {}

func (x *TunnelProfileMutationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_daemon_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelProfileMutationResponse.ProtoReflect.Descriptor instead.
func (*TunnelProfileMutationResponse) Descriptor() ([]byte, []int) {
	return file_rpc_daemon_proto_rawDescGZIP(), []int{15}
}

func (x *TunnelProfileMutationResponse) GetStatus() ResponseStatus {
	if x != nil {
		return x.Status
	}
	return ResponseStatus_Success
}

func (x *TunnelProfileMutationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TunnelProfileMutationResponse) GetData() *TunnelProfile {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteTunnelProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTunnelProfileRequest) Reset() {
	*x = DeleteTunnelProfileRequest{}
	mi := &file_rpc_daemon_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTunnelProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTunnelProfileRequest) ProtoMessage() {}

func (x *DeleteTunnelProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_daemon_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTunnelProfileRequest.ProtoReflect.Descriptor instead.
func (*DeleteTunnelProfileRequest) Descriptor() ([]byte, []int) {
	return file_rpc_daemon_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteTunnelProfileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListConfigurationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SearchPattern string                 `protobuf:"bytes,1,opt,name=search_pattern,json=searchPattern,proto3" json:"search_pattern,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfigurationsRequest) Reset() {
	*x = ListConfigurationsRequest{}
	mi := &file_rpc_daemon_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigurationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigurationsRequest) ProtoMessage() {}

func (x *ListConfigurationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_daemon_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigurationsRequest.ProtoReflect.Descriptor instead.
func (*ListConfigurationsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_daemon_proto_rawDescGZIP(), []int{17}
}

func (x *ListConfigurationsRequest) GetSearchPattern() string {
	if x != nil {
		return x.SearchPattern
	}
	return ""
}

type ListConfigurationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Configs       []*TunnelConfig        `protobuf:"bytes,2,rep,name=configs,proto3" json:"configs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfigurationsResponse) Reset() {
	*x = ListConfigurationsResponse{}
	mi := &file_rpc_daemon_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigurationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigurationsResponse) ProtoMessage() {}

func (x *ListConfigurationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_daemon_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigurationsResponse.ProtoReflect.Descriptor instead.
func (*ListConfigurationsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_daemon_proto_rawDescGZIP(), []int{18}
}

func (x *ListConfigurationsResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ListConfigurationsResponse) GetConfigs() []*TunnelConfig {
	if x != nil {
		return x.Configs
	}
	return nil
}

type ListConfigurationsJSONRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfigurationsJSONRequest) Reset() {
	*x = ListConfigurationsJSONRequest{}
	mi := &file_rpc_daemon_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigurationsJSONRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigurationsJSONRequest) ProtoMessage() {}

func (x *ListConfigurationsJSONRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_daemon_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigurationsJSONRequest.ProtoReflect.Descriptor instead.
func (*ListConfigurationsJSONRequest) Descriptor() ([]byte, []int) {
	return file_rpc_daemon_proto_rawDescGZIP(), []int{19}
}

type ListConfigurationsJSONResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       []*TunnelConfig        `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfigurationsJSONResponse) Reset() {
	*x = ListConfigurationsJSONResponse{}
	mi := &file_rpc_daemon_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigurationsJSONResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigurationsJSONResponse) ProtoMessage() {}

func (x *ListConfigurationsJSONResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_daemon_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigurationsJSONResponse.ProtoReflect.Descriptor instead.
func (*ListConfigurationsJSONResponse) Descriptor() ([]byte, []int) {
	return file_rpc_daemon_proto_rawDescGZIP(), []int{20}
}

func (x *ListConfigurationsJSONResponse) GetConfigs() []*TunnelConfig {
	if x != nil {
		return x.Configs
	}
	return nil
}

type MutationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ResponseStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=daemon.ResponseStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *TunnelConfig          `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutationResponse) Reset() {
	*x = MutationResponse{}
	mi := &file_rpc_daemon_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutationResponse) ProtoMessage() {}

func (x *MutationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_daemon_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutationResponse.ProtoReflect.Descriptor instead.
func (*MutationResponse) Descriptor() ([]byte, []int) {
	return file_rpc_daemon_proto_rawDescGZIP(), []int{21}
}

func (x *MutationResponse) GetStatus() ResponseStatus {
	if x != nil {
		return x.Status
	}
	return ResponseStatus_Success
}

func (x *MutationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MutationResponse) GetData() *TunnelConfig {
	if x != nil {
		return x.Data
	}
	return nil
}

type AddOrUpdateConfigurationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data          *TunnelConfig          `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOrUpdateConfigurationRequest) Reset() {
	*x = AddOrUpdateConfigurationRequest{}
	mi := &file_rpc_daemon_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrUpdateConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrUpdateConfigurationRequest) ProtoMessage() {}

func (x *AddOrUpdateConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_daemon_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrUpdateConfigurationRequest.ProtoReflect.Descriptor instead.
func (*AddOrUpdateConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_rpc_daemon_proto_rawDescGZIP(), []int{22}
}

func (x *AddOrUpdateConfigurationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddOrUpdateConfigurationRequest) GetData() *TunnelConfig {
	if x != nil {
		return x.Data
	}
	return nil
}

type AddOrUpdateConfigurationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Status        ResponseStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=daemon.ResponseStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Data          *TunnelConfig          `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOrUpdateConfigurationResponse) Reset() {
	*x = AddOrUpdateConfigurationResponse{}
	mi := &file_rpc_daemon_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrUpdateConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrUpdateConfigurationResponse) ProtoMessage() {}

func (x *AddOrUpdateConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_daemon_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrUpdateConfigurationResponse.ProtoReflect.Descriptor instead.
func (*AddOrUpdateConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_rpc_daemon_proto_rawDescGZIP(), []int{23}
}

func (x *AddOrUpdateConfigurationResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *AddOrUpdateConfigurationResponse) GetStatus() ResponseStatus {
	if x != nil {
		return x.Status
	}
	return ResponseStatus_Success
}

func (x *AddOrUpdateConfigurationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AddOrUpdateConfigurationResponse) GetData() *TunnelConfig {
	if x != nil {
		return x.Data
	}
	return nil
}

type FetchConfigurationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchConfigurationRequest) Reset() {
	*x = FetchConfigurationRequest{}
	mi := &file_rpc_daemon_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchConfigurationRequest) ProtoMessage() {}

func (x *FetchConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_daemon_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchConfigurationRequest.ProtoReflect.Descriptor instead.
func (*FetchConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_rpc_daemon_proto_rawDescGZIP(), []int{24}
}

func (x *FetchConfigurationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type FetchConfigurationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ResponseStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=daemon.ResponseStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *TunnelConfig          `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchConfigurationResponse) Reset() {
	*x = FetchConfigurationResponse{}
	mi := &file_rpc_daemon_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchConfigurationResponse) ProtoMessage() {}

func (x *FetchConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_daemon_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchConfigurationResponse.ProtoReflect.Descriptor instead.
func (*FetchConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_rpc_daemon_proto_rawDescGZIP(), []int{25}
}

func (x *FetchConfigurationResponse) GetStatus() ResponseStatus {
	if x != nil {
		return x.Status
	}
	return ResponseStatus_Success
}

func (x *FetchConfigurationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FetchConfigurationResponse) GetData() *TunnelConfig {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteConfigurationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConfigurationRequest) Reset() {
	*x = DeleteConfigurationRequest{}
	mi := &file_rpc_daemon_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConfigurationRequest) ProtoMessage() {}

func (x *DeleteConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_daemon_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConfigurationRequest.ProtoReflect.Descriptor instead.
func (*DeleteConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_rpc_daemon_proto_rawDescGZIP(), []int{26}
}

func (x *DeleteConfigurationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteConfigurationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Status        ResponseStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=daemon.ResponseStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConfigurationResponse) Reset() {
	*x = DeleteConfigurationResponse{}
	mi := &file_rpc_daemon_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConfigurationResponse) ProtoMessage() {}

func (x *DeleteConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_daemon_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConfigurationResponse.ProtoReflect.Descriptor instead.
func (*DeleteConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_rpc_daemon_proto_rawDescGZIP(), []int{27}
}

func (x *DeleteConfigurationResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *DeleteConfigurationResponse) GetStatus() ResponseStatus {
	if x != nil {
		return x.Status
	}
	return ResponseStatus_Success
}

func (x *DeleteConfigurationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StartTunnelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigName    string                 `protobuf:"bytes,1,opt,name=config_name,json=configName,proto3" json:"config_name,omitempty"`
	LocalPort     int32                  `protobuf:"varint,2,opt,name=local_port,json=localPort,proto3" json:"local_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTunnelRequest) Reset() {
	*x = StartTunnelRequest{}
	mi := &file_rpc_daemon_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTunnelRequest) ProtoMessage() {}

func (x *StartTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_daemon_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTunnelRequest.ProtoReflect.Descriptor instead.
func (*StartTunnelRequest) Descriptor() ([]byte, []int) {
	return file_rpc_daemon_proto_rawDescGZIP(), []int{28}
}

func (x *StartTunnelRequest) GetConfigName() string {
	if x != nil {
		return x.ConfigName
	}
	return ""
}

func (x *StartTunnelRequest) GetLocalPort() int32 {
	if x != nil {
		return x.LocalPort
	}
	return 0
}

type StartTunnelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Status        ResponseStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=daemon.ResponseStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Events        []string               `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTunnelResponse) Reset() {
	*x = StartTunnelResponse{}
	mi := &file_rpc_daemon_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTunnelResponse) ProtoMessage() {}

func (x *StartTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_daemon_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTunnelResponse.ProtoReflect.Descriptor instead.
func (*StartTunnelResponse) Descriptor() ([]byte, []int) {
	return file_rpc_daemon_proto_rawDescGZIP(), []int{29}
}

func (x *StartTunnelResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *StartTunnelResponse) GetStatus() ResponseStatus {
	if x != nil {
		return x.Status
	}
	return ResponseStatus_Success
}

func (x *StartTunnelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StartTunnelResponse) GetEvents() []string {
	if x != nil {
		return x.Events
	}
	return nil
}

type ListActiveTunnelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActiveTunnelsRequest) Reset() {
	*x = ListActiveTunnelsRequest{}
	mi := &file_rpc_daemon_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveTunnelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveTunnelsRequest) ProtoMessage() {}

func (x *ListActiveTunnelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_daemon_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveTunnelsRequest.ProtoReflect.Descriptor instead.
func (*ListActiveTunnelsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_daemon_proto_rawDescGZIP(), []int{30}
}

type ListActiveTunnelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Tunnels       []*ActiveTunnel        `protobuf:"bytes,2,rep,name=tunnels,proto3" json:"tunnels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActiveTunnelsResponse) Reset() {
	*x = ListActiveTunnelsResponse{}
	mi := &file_rpc_daemon_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveTunnelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveTunnelsResponse) ProtoMessage() {}

func (x *ListActiveTunnelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_daemon_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveTunnelsResponse.ProtoReflect.Descriptor instead.
func (*ListActiveTunnelsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_daemon_proto_rawDescGZIP(), []int{31}
}

func (x *ListActiveTunnelsResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ListActiveTunnelsResponse) GetTunnels() []*ActiveTunnel {
	if x != nil {
		return x.Tunnels
	}
	return nil
}

type ActiveTunnel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	LocalPort     int32                  `protobuf:"varint,2,opt,name=local_port,json=localPort,proto3" json:"local_port,omitempty"`
	RemoteAddr    string                 `protobuf:"bytes,3,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	LocalAddr     string                 `protobuf:"bytes,4,opt,name=local_addr,json=localAddr,proto3" json:"local_addr,omitempty"`
	Server        string                 `protobuf:"bytes,5,opt,name=server,proto3" json:"server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveTunnel) Reset() {
	*x = ActiveTunnel{}
	mi := &file_rpc_daemon_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveTunnel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveTunnel) ProtoMessage() {}

func (x *ActiveTunnel) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_daemon_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveTunnel.ProtoReflect.Descriptor instead.
func (*ActiveTunnel) Descriptor() ([]byte, []int) {
	return file_rpc_daemon_proto_rawDescGZIP(), []int{32}
}

func (x *ActiveTunnel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ActiveTunnel) GetLocalPort() int32 {
	if x != nil {
		return x.LocalPort
	}
	return 0
}

func (x *ActiveTunnel) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *ActiveTunnel) GetLocalAddr() string {
	if x != nil {
		return x.LocalAddr
	}
	return ""
}

func (x *ActiveTunnel) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

type ListActiveTunnelsJSONRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActiveTunnelsJSONRequest) Reset() {
	*x = ListActiveTunnelsJSONRequest{}
	mi := &file_rpc_daemon_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveTunnelsJSONRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveTunnelsJSONRequest) ProtoMessage() {}

func (x *ListActiveTunnelsJSONRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_daemon_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveTunnelsJSONRequest.ProtoReflect.Descriptor instead.
func (*ListActiveTunnelsJSONRequest) Descriptor() ([]byte, []int) {
	return file_rpc_daemon_proto_rawDescGZIP(), []int{33}
}

type ListActiveTunnelsJSONResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tunnels       []*ActiveTunnel        `protobuf:"bytes,1,rep,name=tunnels,proto3" json:"tunnels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActiveTunnelsJSONResponse) Reset() {
	*x = ListActiveTunnelsJSONResponse{}
	mi := &file_rpc_daemon_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveTunnelsJSONResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveTunnelsJSONResponse) ProtoMessage() {}

func (x *ListActiveTunnelsJSONResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_daemon_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveTunnelsJSONResponse.ProtoReflect.Descriptor instead.
func (*ListActiveTunnelsJSONResponse) Descriptor() ([]byte, []int) {
	return file_rpc_daemon_proto_rawDescGZIP(), []int{34}
}

func (x *ListActiveTunnelsJSONResponse) GetTunnels() []*ActiveTunnel {
	if x != nil {
		return x.Tunnels
	}
	return nil
}

type KillTunnelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigName    string                 `protobuf:"bytes,1,opt,name=config_name,json=configName,proto3" json:"config_name,omitempty"`
	LocalPort     int32                  `protobuf:"varint,2,opt,name=local_port,json=localPort,proto3" json:"local_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillTunnelRequest) Reset() {
	*x = KillTunnelRequest{}
	mi := &file_rpc_daemon_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillTunnelRequest) ProtoMessage() {}

func (x *KillTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_daemon_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillTunnelRequest.ProtoReflect.Descriptor instead.
func (*KillTunnelRequest) Descriptor() ([]byte, []int) {
	return file_rpc_daemon_proto_rawDescGZIP(), []int{35}
}

func (x *KillTunnelRequest) GetConfigName() string {
	if x != nil {
		return x.ConfigName
	}
	return ""
}

func (x *KillTunnelRequest) GetLocalPort() int32 {
	if x != nil {
		return x.LocalPort
	}
	return 0
}

type KillTunnelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Status        ResponseStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=daemon.ResponseStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillTunnelResponse) Reset() {
	*x = KillTunnelResponse{}
	mi := &file_rpc_daemon_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillTunnelResponse) ProtoMessage() {}

func (x *KillTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_daemon_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillTunnelResponse.ProtoReflect.Descriptor instead.
func (*KillTunnelResponse) Descriptor() ([]byte, []int) {
	return file_rpc_daemon_proto_rawDescGZIP(), []int{36}
}

func (x *KillTunnelResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *KillTunnelResponse) GetStatus() ResponseStatus {
	if x != nil {
		return x.Status
	}
	return ResponseStatus_Success
}

func (x *KillTunnelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_rpc_daemon_proto protoreflect.FileDescriptor

const file_rpc_daemon_proto_rawDesc = "" +
	"\n" +
	"\x10rpc/daemon.proto\x12\x06daemon\"\xec\x01\n" +
	"\fTunnelConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06server\x18\x03 \x01(\tR\x06server\x12\x12\n" +
	"\x04user\x18\x04 \x01(\tR\x04user\x12\x19\n" +
	"\bkey_file\x18\x05 \x01(\tR\akeyFile\x12\x1f\n" +
	"\vremote_host\x18\x06 \x01(\tR\n" +
	"remoteHost\x12\x1f\n" +
	"\vremote_port\x18\a \x01(\x05R\n" +
	"remotePort\x12\x1d\n" +
	"\n" +
	"local_port\x18\b \x01(\x05R\tlocalPort\"t\n" +
	"\aMachine\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06server\x18\x03 \x01(\tR\x06server\x12\x12\n" +
	"\x04user\x18\x04 \x01(\tR\x04user\x12\x19\n" +
	"\bkey_file\x18\x05 \x01(\tR\akeyFile\"\x91\x02\n" +
	"\rTunnelProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x04 \x01(\tR\tmachineId\x12\x1f\n" +
	"\vremote_host\x18\x05 \x01(\tR\n" +
	"remoteHost\x12\x1f\n" +
	"\vremote_port\x18\x06 \x01(\x05R\n" +
	"remotePort\x12\x1d\n" +
	"\n" +
	"local_port\x18\a \x01(\x05R\tlocalPort\x12.\n" +
	"\amachine\x18\b \x01(\v2\x0f.daemon.MachineH\x00R\amachine\x88\x01\x01B\n" +
	"\n" +
	"\b_machine\"\x15\n" +
	"\x13ListMachinesRequest\"\x8d\x01\n" +
	"\x14ListMachinesResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\x0e2\x16.daemon.ResponseStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\bmachines\x18\x03 \x03(\v2\x0f.daemon.MachineR\bmachines\"#\n" +
	"\x11GetMachineRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x83\x01\n" +
	"\x12GetMachineResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\x0e2\x16.daemon.ResponseStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\x04data\x18\x03 \x01(\v2\x0f.daemon.MachineR\x04data\"M\n" +
	"\x16MachineMutationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\x04data\x18\x02 \x01(\v2\x0f.daemon.MachineR\x04data\"\x88\x01\n" +
	"\x17MachineMutationResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\x0e2\x16.daemon.ResponseStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\x04data\x18\x03 \x01(\v2\x0f.daemon.MachineR\x04data\"&\n" +
	"\x14DeleteMachineRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1b\n" +
	"\x19ListTunnelProfilesRequest\"\xa6\x01\n" +
	"\x1aListTunnelProfilesResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\x0e2\x16.daemon.ResponseStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12>\n" +
	"\x0ftunnel_profiles\x18\x03 \x03(\v2\x15.daemon.TunnelProfileR\x0etunnelProfiles\")\n" +
	"\x17GetTunnelProfileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x8f\x01\n" +
	"\x18GetTunnelProfileResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\x0e2\x16.daemon.ResponseStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x04data\x18\x03 \x01(\v2\x15.daemon.TunnelProfileR\x04data\"Y\n" +
	"\x1cTunnelProfileMutationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x04data\x18\x02 \x01(\v2\x15.daemon.TunnelProfileR\x04data\"\x94\x01\n" +
	"\x1dTunnelProfileMutationResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\x0e2\x16.daemon.ResponseStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x04data\x18\x03 \x01(\v2\x15.daemon.TunnelProfileR\x04data\",\n" +
	"\x1aDeleteTunnelProfileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"B\n" +
	"\x19ListConfigurationsRequest\x12%\n" +
	"\x0esearch_pattern\x18\x01 \x01(\tR\rsearchPattern\"d\n" +
	"\x1aListConfigurationsResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12.\n" +
	"\aconfigs\x18\x02 \x03(\v2\x14.daemon.TunnelConfigR\aconfigs\"\x1f\n" +
	"\x1dListConfigurationsJSONRequest\"P\n" +
	"\x1eListConfigurationsJSONResponse\x12.\n" +
	"\aconfigs\x18\x01 \x03(\v2\x14.daemon.TunnelConfigR\aconfigs\"\x86\x01\n" +
	"\x10MutationResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\x0e2\x16.daemon.ResponseStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x14.daemon.TunnelConfigR\x04data\"_\n" +
	"\x1fAddOrUpdateConfigurationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12(\n" +
	"\x04data\x18\x02 \x01(\v2\x14.daemon.TunnelConfigR\x04data\"\xae\x01\n" +
	" AddOrUpdateConfigurationResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12.\n" +
	"\x06status\x18\x02 \x01(\x0e2\x16.daemon.ResponseStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12(\n" +
	"\x04data\x18\x04 \x01(\v2\x14.daemon.TunnelConfigR\x04data\"/\n" +
	"\x19FetchConfigurationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x90\x01\n" +
	"\x1aFetchConfigurationResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\x0e2\x16.daemon.ResponseStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x14.daemon.TunnelConfigR\x04data\"0\n" +
	"\x1aDeleteConfigurationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x7f\n" +
	"\x1bDeleteConfigurationResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12.\n" +
	"\x06status\x18\x02 \x01(\x0e2\x16.daemon.ResponseStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"T\n" +
	"\x12StartTunnelRequest\x12\x1f\n" +
	"\vconfig_name\x18\x01 \x01(\tR\n" +
	"configName\x12\x1d\n" +
	"\n" +
	"local_port\x18\x02 \x01(\x05R\tlocalPort\"\x8f\x01\n" +
	"\x13StartTunnelResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12.\n" +
	"\x06status\x18\x02 \x01(\x0e2\x16.daemon.ResponseStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x16\n" +
	"\x06events\x18\x04 \x03(\tR\x06events\"\x1a\n" +
	"\x18ListActiveTunnelsRequest\"c\n" +
	"\x19ListActiveTunnelsResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12.\n" +
	"\atunnels\x18\x02 \x03(\v2\x14.daemon.ActiveTunnelR\atunnels\"\x99\x01\n" +
	"\fActiveTunnel\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"local_port\x18\x02 \x01(\x05R\tlocalPort\x12\x1f\n" +
	"\vremote_addr\x18\x03 \x01(\tR\n" +
	"remoteAddr\x12\x1d\n" +
	"\n" +
	"local_addr\x18\x04 \x01(\tR\tlocalAddr\x12\x16\n" +
	"\x06server\x18\x05 \x01(\tR\x06server\"\x1e\n" +
	"\x1cListActiveTunnelsJSONRequest\"O\n" +
	"\x1dListActiveTunnelsJSONResponse\x12.\n" +
	"\atunnels\x18\x01 \x03(\v2\x14.daemon.ActiveTunnelR\atunnels\"S\n" +
	"\x11KillTunnelRequest\x12\x1f\n" +
	"\vconfig_name\x18\x01 \x01(\tR\n" +
	"configName\x12\x1d\n" +
	"\n" +
	"local_port\x18\x02 \x01(\x05R\tlocalPort\"v\n" +
	"\x12KillTunnelResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12.\n" +
	"\x06status\x18\x02 \x01(\x0e2\x16.daemon.ResponseStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage*(\n" +
	"\x0eResponseStatus\x12\v\n" +
	"\aSuccess\x10\x00\x12\t\n" +
	"\x05Error\x10\x012\xcc\x10\n" +
	"\rDaemonService\x12]\n" +
	"\x12ListConfigurations\x12!.daemon.ListConfigurationsRequest\x1a\".daemon.ListConfigurationsResponse\"\x00\x12i\n" +
	"\x16ListConfigurationsJSON\x12%.daemon.ListConfigurationsJSONRequest\x1a&.daemon.ListConfigurationsJSONResponse\"\x00\x12g\n" +
	"\x10AddConfiguration\x12'.daemon.AddOrUpdateConfigurationRequest\x1a(.daemon.AddOrUpdateConfigurationResponse\"\x00\x12[\n" +
	"\x14AddConfigurationJSON\x12'.daemon.AddOrUpdateConfigurationRequest\x1a\x18.daemon.MutationResponse\"\x00\x12j\n" +
	"\x13UpdateConfiguration\x12'.daemon.AddOrUpdateConfigurationRequest\x1a(.daemon.AddOrUpdateConfigurationResponse\"\x00\x12^\n" +
	"\x17UpdateConfigurationJSON\x12'.daemon.AddOrUpdateConfigurationRequest\x1a\x18.daemon.MutationResponse\"\x00\x12]\n" +
	"\x12FetchConfiguration\x12!.daemon.FetchConfigurationRequest\x1a\".daemon.FetchConfigurationResponse\"\x00\x12`\n" +
	"\x13DeleteConfiguration\x12\".daemon.DeleteConfigurationRequest\x1a#.daemon.DeleteConfigurationResponse\"\x00\x12Y\n" +
	"\x17DeleteConfigurationJSON\x12\".daemon.DeleteConfigurationRequest\x1a\x18.daemon.MutationResponse\"\x00\x12H\n" +
	"\vStartTunnel\x12\x1a.daemon.StartTunnelRequest\x1a\x1b.daemon.StartTunnelResponse\"\x00\x12E\n" +
	"\n" +
	"KillTunnel\x12\x19.daemon.KillTunnelRequest\x1a\x1a.daemon.KillTunnelResponse\"\x00\x12Z\n" +
	"\x11ListActiveTunnels\x12 .daemon.ListActiveTunnelsRequest\x1a!.daemon.ListActiveTunnelsResponse\"\x00\x12f\n" +
	"\x15ListActiveTunnelsJSON\x12$.daemon.ListActiveTunnelsJSONRequest\x1a%.daemon.ListActiveTunnelsJSONResponse\"\x00\x12K\n" +
	"\fListMachines\x12\x1b.daemon.ListMachinesRequest\x1a\x1c.daemon.ListMachinesResponse\"\x00\x12E\n" +
	"\n" +
	"GetMachine\x12\x19.daemon.GetMachineRequest\x1a\x1a.daemon.GetMachineResponse\"\x00\x12O\n" +
	"\n" +
	"AddMachine\x12\x1e.daemon.MachineMutationRequest\x1a\x1f.daemon.MachineMutationResponse\"\x00\x12R\n" +
	"\rUpdateMachine\x12\x1e.daemon.MachineMutationRequest\x1a\x1f.daemon.MachineMutationResponse\"\x00\x12P\n" +
	"\rDeleteMachine\x12\x1c.daemon.DeleteMachineRequest\x1a\x1f.daemon.MachineMutationResponse\"\x00\x12]\n" +
	"\x12ListTunnelProfiles\x12!.daemon.ListTunnelProfilesRequest\x1a\".daemon.ListTunnelProfilesResponse\"\x00\x12W\n" +
	"\x10GetTunnelProfile\x12\x1f.daemon.GetTunnelProfileRequest\x1a .daemon.GetTunnelProfileResponse\"\x00\x12a\n" +
	"\x10AddTunnelProfile\x12$.daemon.TunnelProfileMutationRequest\x1a%.daemon.TunnelProfileMutationResponse\"\x00\x12d\n" +
	"\x13UpdateTunnelProfile\x12$.daemon.TunnelProfileMutationRequest\x1a%.daemon.TunnelProfileMutationResponse\"\x00\x12b\n" +
	"\x13DeleteTunnelProfile\x12\".daemon.DeleteTunnelProfileRequest\x1a%.daemon.TunnelProfileMutationResponse\"\x00B/Z-github.com/besrabasant/ssh-tunnel-manager/rpcb\x06proto3"

var (
	file_rpc_daemon_proto_rawDescOnce sync.Once
	file_rpc_daemon_proto_rawDescData []byte
)

func file_rpc_daemon_proto_rawDescGZIP() []byte {
	file_rpc_daemon_proto_rawDescOnce.Do(func() {
		file_rpc_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_daemon_proto_rawDesc), len(file_rpc_daemon_proto_rawDesc)))
	})
	return file_rpc_daemon_proto_rawDescData
}

var file_rpc_daemon_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rpc_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_rpc_daemon_proto_goTypes = []any{
	(ResponseStatus)(0),                      // 0: daemon.ResponseStatus
	(*TunnelConfig)(nil),                     // 1: daemon.TunnelConfig
	(*Machine)(nil),                          // 2: daemon.Machine
	(*TunnelProfile)(nil),                    // 3: daemon.TunnelProfile
	(*ListMachinesRequest)(nil),              // 4: daemon.ListMachinesRequest
	(*ListMachinesResponse)(nil),             // 5: daemon.ListMachinesResponse
	(*GetMachineRequest)(nil),                // 6: daemon.GetMachineRequest
	(*GetMachineResponse)(nil),               // 7: daemon.GetMachineResponse
	(*MachineMutationRequest)(nil),           // 8: daemon.MachineMutationRequest
	(*MachineMutationResponse)(nil),          // 9: daemon.MachineMutationResponse
	(*DeleteMachineRequest)(nil),             // 10: daemon.DeleteMachineRequest
	(*ListTunnelProfilesRequest)(nil),        // 11: daemon.ListTunnelProfilesRequest
	(*ListTunnelProfilesResponse)(nil),       // 12: daemon.ListTunnelProfilesResponse
	(*GetTunnelProfileRequest)(nil),          // 13: daemon.GetTunnelProfileRequest
	(*GetTunnelProfileResponse)(nil),         // 14: daemon.GetTunnelProfileResponse
	(*TunnelProfileMutationRequest)(nil),     // 15: daemon.TunnelProfileMutationRequest
	(*TunnelProfileMutationResponse)(nil),    // 16: daemon.TunnelProfileMutationResponse
	(*DeleteTunnelProfileRequest)(nil),       // 17: daemon.DeleteTunnelProfileRequest
	(*ListConfigurationsRequest)(nil),        // 18: daemon.ListConfigurationsRequest
	(*ListConfigurationsResponse)(nil),       // 19: daemon.ListConfigurationsResponse
	(*ListConfigurationsJSONRequest)(nil),    // 20: daemon.ListConfigurationsJSONRequest
	(*ListConfigurationsJSONResponse)(nil),   // 21: daemon.ListConfigurationsJSONResponse
	(*MutationResponse)(nil),                 // 22: daemon.MutationResponse
	(*AddOrUpdateConfigurationRequest)(nil),  // 23: daemon.AddOrUpdateConfigurationRequest
	(*AddOrUpdateConfigurationResponse)(nil), // 24: daemon.AddOrUpdateConfigurationResponse
	(*FetchConfigurationRequest)(nil),        // 25: daemon.FetchConfigurationRequest
	(*FetchConfigurationResponse)(nil),       // 26: daemon.FetchConfigurationResponse
	(*DeleteConfigurationRequest)(nil),       // 27: daemon.DeleteConfigurationRequest
	(*DeleteConfigurationResponse)(nil),      // 28: daemon.DeleteConfigurationResponse
	(*StartTunnelRequest)(nil),               // 29: daemon.StartTunnelRequest
	(*StartTunnelResponse)(nil),              // 30: daemon.StartTunnelResponse
	(*ListActiveTunnelsRequest)(nil),         // 31: daemon.ListActiveTunnelsRequest
	(*ListActiveTunnelsResponse)(nil),        // 32: daemon.ListActiveTunnelsResponse
	(*ActiveTunnel)(nil),                     // 33: daemon.ActiveTunnel
	(*ListActiveTunnelsJSONRequest)(nil),     // 34: daemon.ListActiveTunnelsJSONRequest
	(*ListActiveTunnelsJSONResponse)(nil),    // 35: daemon.ListActiveTunnelsJSONResponse
	(*KillTunnelRequest)(nil),                // 36: daemon.KillTunnelRequest
	(*KillTunnelResponse)(nil),               // 37: daemon.KillTunnelResponse
}
var file_rpc_daemon_proto_depIdxs = []int32{
	2,  // 0: daemon.TunnelProfile.machine:type_name -> daemon.Machine
	0,  // 1: daemon.ListMachinesResponse.status:type_name -> daemon.ResponseStatus
	2,  // 2: daemon.ListMachinesResponse.machines:type_name -> daemon.Machine
	0,  // 3: daemon.GetMachineResponse.status:type_name -> daemon.ResponseStatus
	2,  // 4: daemon.GetMachineResponse.data:type_name -> daemon.Machine
	2,  // 5: daemon.MachineMutationRequest.data:type_name -> daemon.Machine
	0,  // 6: daemon.MachineMutationResponse.status:type_name -> daemon.ResponseStatus
	2,  // 7: daemon.MachineMutationResponse.data:type_name -> daemon.Machine
	0,  // 8: daemon.ListTunnelProfilesResponse.status:type_name -> daemon.ResponseStatus
	3,  // 9: daemon.ListTunnelProfilesResponse.tunnel_profiles:type_name -> daemon.TunnelProfile
	0,  // 10: daemon.GetTunnelProfileResponse.status:type_name -> daemon.ResponseStatus
	3,  // 11: daemon.GetTunnelProfileResponse.data:type_name -> daemon.TunnelProfile
	3,  // 12: daemon.TunnelProfileMutationRequest.data:type_name -> daemon.TunnelProfile
	0,  // 13: daemon.TunnelProfileMutationResponse.status:type_name -> daemon.ResponseStatus
	3,  // 14: daemon.TunnelProfileMutationResponse.data:type_name -> daemon.TunnelProfile
	1,  // 15: daemon.ListConfigurationsResponse.configs:type_name -> daemon.TunnelConfig
	1,  // 16: daemon.ListConfigurationsJSONResponse.configs:type_name -> daemon.TunnelConfig
	0,  // 17: daemon.MutationResponse.status:type_name -> daemon.ResponseStatus
	1,  // 18: daemon.MutationResponse.data:type_name -> daemon.TunnelConfig
	1,  // 19: daemon.AddOrUpdateConfigurationRequest.data:type_name -> daemon.TunnelConfig
	0,  // 20: daemon.AddOrUpdateConfigurationResponse.status:type_name -> daemon.ResponseStatus
	1,  // 21: daemon.AddOrUpdateConfigurationResponse.data:type_name -> daemon.TunnelConfig
	0,  // 22: daemon.FetchConfigurationResponse.status:type_name -> daemon.ResponseStatus
	1,  // 23: daemon.FetchConfigurationResponse.data:type_name -> daemon.TunnelConfig
	0,  // 24: daemon.DeleteConfigurationResponse.status:type_name -> daemon.ResponseStatus
	0,  // 25: daemon.StartTunnelResponse.status:type_name -> daemon.ResponseStatus
	33, // 26: daemon.ListActiveTunnelsResponse.tunnels:type_name -> daemon.ActiveTunnel
	33, // 27: daemon.ListActiveTunnelsJSONResponse.tunnels:type_name -> daemon.ActiveTunnel
	0,  // 28: daemon.KillTunnelResponse.status:type_name -> daemon.ResponseStatus
	18, // 29: daemon.DaemonService.ListConfigurations:input_type -> daemon.ListConfigurationsRequest
	20, // 30: daemon.DaemonService.ListConfigurationsJSON:input_type -> daemon.ListConfigurationsJSONRequest
	23, // 31: daemon.DaemonService.AddConfiguration:input_type -> daemon.AddOrUpdateConfigurationRequest
	23, // 32: daemon.DaemonService.AddConfigurationJSON:input_type -> daemon.AddOrUpdateConfigurationRequest
	23, // 33: daemon.DaemonService.UpdateConfiguration:input_type -> daemon.AddOrUpdateConfigurationRequest
	23, // 34: daemon.DaemonService.UpdateConfigurationJSON:input_type -> daemon.AddOrUpdateConfigurationRequest
	25, // 35: daemon.DaemonService.FetchConfiguration:input_type -> daemon.FetchConfigurationRequest
	27, // 36: daemon.DaemonService.DeleteConfiguration:input_type -> daemon.DeleteConfigurationRequest
	27, // 37: daemon.DaemonService.DeleteConfigurationJSON:input_type -> daemon.DeleteConfigurationRequest
	29, // 38: daemon.DaemonService.StartTunnel:input_type -> daemon.StartTunnelRequest
	36, // 39: daemon.DaemonService.KillTunnel:input_type -> daemon.KillTunnelRequest
	31, // 40: daemon.DaemonService.ListActiveTunnels:input_type -> daemon.ListActiveTunnelsRequest
	34, // 41: daemon.DaemonService.ListActiveTunnelsJSON:input_type -> daemon.ListActiveTunnelsJSONRequest
	4,  // 42: daemon.DaemonService.ListMachines:input_type -> daemon.ListMachinesRequest
	6,  // 43: daemon.DaemonService.GetMachine:input_type -> daemon.GetMachineRequest
	8,  // 44: daemon.DaemonService.AddMachine:input_type -> daemon.MachineMutationRequest
	8,  // 45: daemon.DaemonService.UpdateMachine:input_type -> daemon.MachineMutationRequest
	10, // 46: daemon.DaemonService.DeleteMachine:input_type -> daemon.DeleteMachineRequest
	11, // 47: daemon.DaemonService.ListTunnelProfiles:input_type -> daemon.ListTunnelProfilesRequest
	13, // 48: daemon.DaemonService.GetTunnelProfile:input_type -> daemon.GetTunnelProfileRequest
	15, // 49: daemon.DaemonService.AddTunnelProfile:input_type -> daemon.TunnelProfileMutationRequest
	15, // 50: daemon.DaemonService.UpdateTunnelProfile:input_type -> daemon.TunnelProfileMutationRequest
	17, // 51: daemon.DaemonService.DeleteTunnelProfile:input_type -> daemon.DeleteTunnelProfileRequest
	19, // 52: daemon.DaemonService.ListConfigurations:output_type -> daemon.ListConfigurationsResponse
	21, // 53: daemon.DaemonService.ListConfigurationsJSON:output_type -> daemon.ListConfigurationsJSONResponse
	24, // 54: daemon.DaemonService.AddConfiguration:output_type -> daemon.AddOrUpdateConfigurationResponse
	22, // 55: daemon.DaemonService.AddConfigurationJSON:output_type -> daemon.MutationResponse
	24, // 56: daemon.DaemonService.UpdateConfiguration:output_type -> daemon.AddOrUpdateConfigurationResponse
	22, // 57: daemon.DaemonService.UpdateConfigurationJSON:output_type -> daemon.MutationResponse
	26, // 58: daemon.DaemonService.FetchConfiguration:output_type -> daemon.FetchConfigurationResponse
	28, // 59: daemon.DaemonService.DeleteConfiguration:output_type -> daemon.DeleteConfigurationResponse
	22, // 60: daemon.DaemonService.DeleteConfigurationJSON:output_type -> daemon.MutationResponse
	30, // 61: daemon.DaemonService.StartTunnel:output_type -> daemon.StartTunnelResponse
	37, // 62: daemon.DaemonService.KillTunnel:output_type -> daemon.KillTunnelResponse
	32, // 63: daemon.DaemonService.ListActiveTunnels:output_type -> daemon.ListActiveTunnelsResponse
	35, // 64: daemon.DaemonService.ListActiveTunnelsJSON:output_type -> daemon.ListActiveTunnelsJSONResponse
	5,  // 65: daemon.DaemonService.ListMachines:output_type -> daemon.ListMachinesResponse
	7,  // 66: daemon.DaemonService.GetMachine:output_type -> daemon.GetMachineResponse
	9,  // 67: daemon.DaemonService.AddMachine:output_type -> daemon.MachineMutationResponse
	9,  // 68: daemon.DaemonService.UpdateMachine:output_type -> daemon.MachineMutationResponse
	9,  // 69: daemon.DaemonService.DeleteMachine:output_type -> daemon.MachineMutationResponse
	12, // 70: daemon.DaemonService.ListTunnelProfiles:output_type -> daemon.ListTunnelProfilesResponse
	14, // 71: daemon.DaemonService.GetTunnelProfile:output_type -> daemon.GetTunnelProfileResponse
	16, // 72: daemon.DaemonService.AddTunnelProfile:output_type -> daemon.TunnelProfileMutationResponse
	16, // 73: daemon.DaemonService.UpdateTunnelProfile:output_type -> daemon.TunnelProfileMutationResponse
	16, // 74: daemon.DaemonService.DeleteTunnelProfile:output_type -> daemon.TunnelProfileMutationResponse
	52, // [52:75] is the sub-list for method output_type
	29, // [29:52] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_rpc_daemon_proto_init() }
func file_rpc_daemon_proto_init() {
	if File_rpc_daemon_proto != nil {
		return
	}
	file_rpc_daemon_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_daemon_proto_rawDesc), len(file_rpc_daemon_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_daemon_proto_goTypes,
		DependencyIndexes: file_rpc_daemon_proto_depIdxs,
		EnumInfos:         file_rpc_daemon_proto_enumTypes,
		MessageInfos:      file_rpc_daemon_proto_msgTypes,
	}.Build()
	File_rpc_daemon_proto = out.File
	file_rpc_daemon_proto_goTypes = nil
	file_rpc_daemon_proto_depIdxs = nil
}
