// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v7.36.1
// source: rpc/daemon.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DaemonServiceClient is the client API for DaemonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DaemonServiceClient interface {
	ListConfigurations(ctx context.Context, in *ListConfigurationsRequest, opts ...grpc.CallOption) (*ListConfigurationsResponse, error)
	ListConfigurationsJSON(ctx context.Context, in *ListConfigurationsJSONRequest, opts ...grpc.CallOption) (*ListConfigurationsJSONResponse, error)
	AddConfiguration(ctx context.Context, in *AddOrUpdateConfigurationRequest, opts ...grpc.CallOption) (*AddOrUpdateConfigurationResponse, error)
	AddConfigurationJSON(ctx context.Context, in *AddOrUpdateConfigurationRequest, opts ...grpc.CallOption) (*MutationResponse, error)
	UpdateConfiguration(ctx context.Context, in *AddOrUpdateConfigurationRequest, opts ...grpc.CallOption) (*AddOrUpdateConfigurationResponse, error)
	UpdateConfigurationJSON(ctx context.Context, in *AddOrUpdateConfigurationRequest, opts ...grpc.CallOption) (*MutationResponse, error)
	FetchConfiguration(ctx context.Context, in *FetchConfigurationRequest, opts ...grpc.CallOption) (*FetchConfigurationResponse, error)
	DeleteConfiguration(ctx context.Context, in *DeleteConfigurationRequest, opts ...grpc.CallOption) (*DeleteConfigurationResponse, error)
	DeleteConfigurationJSON(ctx context.Context, in *DeleteConfigurationRequest, opts ...grpc.CallOption) (*MutationResponse, error)
	StartTunnel(ctx context.Context, in *StartTunnelRequest, opts ...grpc.CallOption) (*StartTunnelResponse, error)
	KillTunnel(ctx context.Context, in *KillTunnelRequest, opts ...grpc.CallOption) (*KillTunnelResponse, error)
	ListActiveTunnels(ctx context.Context, in *ListActiveTunnelsRequest, opts ...grpc.CallOption) (*ListActiveTunnelsResponse, error)
	ListActiveTunnelsJSON(ctx context.Context, in *ListActiveTunnelsJSONRequest, opts ...grpc.CallOption) (*ListActiveTunnelsJSONResponse, error)
	ListMachines(ctx context.Context, in *ListMachinesRequest, opts ...grpc.CallOption) (*ListMachinesResponse, error)
	GetMachine(ctx context.Context, in *GetMachineRequest, opts ...grpc.CallOption) (*GetMachineResponse, error)
	AddMachine(ctx context.Context, in *MachineMutationRequest, opts ...grpc.CallOption) (*MachineMutationResponse, error)
	UpdateMachine(ctx context.Context, in *MachineMutationRequest, opts ...grpc.CallOption) (*MachineMutationResponse, error)
	DeleteMachine(ctx context.Context, in *DeleteMachineRequest, opts ...grpc.CallOption) (*MachineMutationResponse, error)
	ListTunnelProfiles(ctx context.Context, in *ListTunnelProfilesRequest, opts ...grpc.CallOption) (*ListTunnelProfilesResponse, error)
	GetTunnelProfile(ctx context.Context, in *GetTunnelProfileRequest, opts ...grpc.CallOption) (*GetTunnelProfileResponse, error)
	AddTunnelProfile(ctx context.Context, in *TunnelProfileMutationRequest, opts ...grpc.CallOption) (*TunnelProfileMutationResponse, error)
	UpdateTunnelProfile(ctx context.Context, in *TunnelProfileMutationRequest, opts ...grpc.CallOption) (*TunnelProfileMutationResponse, error)
	DeleteTunnelProfile(ctx context.Context, in *DeleteTunnelProfileRequest, opts ...grpc.CallOption) (*TunnelProfileMutationResponse, error)
}

type daemonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDaemonServiceClient(cc grpc.ClientConnInterface) DaemonServiceClient {
	return &daemonServiceClient{cc}
}

func (c *daemonServiceClient) ListConfigurations(ctx context.Context, in *ListConfigurationsRequest, opts ...grpc.CallOption) (*ListConfigurationsResponse, error) {
	out := new(ListConfigurationsResponse)
	err := c.cc.Invoke(ctx, "/daemon.DaemonService/ListConfigurations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ListConfigurationsJSON(ctx context.Context, in *ListConfigurationsJSONRequest, opts ...grpc.CallOption) (*ListConfigurationsJSONResponse, error) {
	out := new(ListConfigurationsJSONResponse)
	err := c.cc.Invoke(ctx, "/daemon.DaemonService/ListConfigurationsJSON", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) AddConfiguration(ctx context.Context, in *AddOrUpdateConfigurationRequest, opts ...grpc.CallOption) (*AddOrUpdateConfigurationResponse, error) {
	out := new(AddOrUpdateConfigurationResponse)
	err := c.cc.Invoke(ctx, "/daemon.DaemonService/AddConfiguration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) AddConfigurationJSON(ctx context.Context, in *AddOrUpdateConfigurationRequest, opts ...grpc.CallOption) (*MutationResponse, error) {
	out := new(MutationResponse)
	err := c.cc.Invoke(ctx, "/daemon.DaemonService/AddConfigurationJSON", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) UpdateConfiguration(ctx context.Context, in *AddOrUpdateConfigurationRequest, opts ...grpc.CallOption) (*AddOrUpdateConfigurationResponse, error) {
	out := new(AddOrUpdateConfigurationResponse)
	err := c.cc.Invoke(ctx, "/daemon.DaemonService/UpdateConfiguration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) UpdateConfigurationJSON(ctx context.Context, in *AddOrUpdateConfigurationRequest, opts ...grpc.CallOption) (*MutationResponse, error) {
	out := new(MutationResponse)
	err := c.cc.Invoke(ctx, "/daemon.DaemonService/UpdateConfigurationJSON", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) FetchConfiguration(ctx context.Context, in *FetchConfigurationRequest, opts ...grpc.CallOption) (*FetchConfigurationResponse, error) {
	out := new(FetchConfigurationResponse)
	err := c.cc.Invoke(ctx, "/daemon.DaemonService/FetchConfiguration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) DeleteConfiguration(ctx context.Context, in *DeleteConfigurationRequest, opts ...grpc.CallOption) (*DeleteConfigurationResponse, error) {
	out := new(DeleteConfigurationResponse)
	err := c.cc.Invoke(ctx, "/daemon.DaemonService/DeleteConfiguration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) DeleteConfigurationJSON(ctx context.Context, in *DeleteConfigurationRequest, opts ...grpc.CallOption) (*MutationResponse, error) {
	out := new(MutationResponse)
	err := c.cc.Invoke(ctx, "/daemon.DaemonService/DeleteConfigurationJSON", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) StartTunnel(ctx context.Context, in *StartTunnelRequest, opts ...grpc.CallOption) (*StartTunnelResponse, error) {
	out := new(StartTunnelResponse)
	err := c.cc.Invoke(ctx, "/daemon.DaemonService/StartTunnel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) KillTunnel(ctx context.Context, in *KillTunnelRequest, opts ...grpc.CallOption) (*KillTunnelResponse, error) {
	out := new(KillTunnelResponse)
	err := c.cc.Invoke(ctx, "/daemon.DaemonService/KillTunnel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ListActiveTunnels(ctx context.Context, in *ListActiveTunnelsRequest, opts ...grpc.CallOption) (*ListActiveTunnelsResponse, error) {
	out := new(ListActiveTunnelsResponse)
	err := c.cc.Invoke(ctx, "/daemon.DaemonService/ListActiveTunnels", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ListActiveTunnelsJSON(ctx context.Context, in *ListActiveTunnelsJSONRequest, opts ...grpc.CallOption) (*ListActiveTunnelsJSONResponse, error) {
	out := new(ListActiveTunnelsJSONResponse)
	err := c.cc.Invoke(ctx, "/daemon.DaemonService/ListActiveTunnelsJSON", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ListMachines(ctx context.Context, in *ListMachinesRequest, opts ...grpc.CallOption) (*ListMachinesResponse, error) {
	out := new(ListMachinesResponse)
	err := c.cc.Invoke(ctx, "/daemon.DaemonService/ListMachines", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetMachine(ctx context.Context, in *GetMachineRequest, opts ...grpc.CallOption) (*GetMachineResponse, error) {
	out := new(GetMachineResponse)
	err := c.cc.Invoke(ctx, "/daemon.DaemonService/GetMachine", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) AddMachine(ctx context.Context, in *MachineMutationRequest, opts ...grpc.CallOption) (*MachineMutationResponse, error) {
	out := new(MachineMutationResponse)
	err := c.cc.Invoke(ctx, "/daemon.DaemonService/AddMachine", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) UpdateMachine(ctx context.Context, in *MachineMutationRequest, opts ...grpc.CallOption) (*MachineMutationResponse, error) {
	out := new(MachineMutationResponse)
	err := c.cc.Invoke(ctx, "/daemon.DaemonService/UpdateMachine", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) DeleteMachine(ctx context.Context, in *DeleteMachineRequest, opts ...grpc.CallOption) (*MachineMutationResponse, error) {
	out := new(MachineMutationResponse)
	err := c.cc.Invoke(ctx, "/daemon.DaemonService/DeleteMachine", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ListTunnelProfiles(ctx context.Context, in *ListTunnelProfilesRequest, opts ...grpc.CallOption) (*ListTunnelProfilesResponse, error) {
	out := new(ListTunnelProfilesResponse)
	err := c.cc.Invoke(ctx, "/daemon.DaemonService/ListTunnelProfiles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetTunnelProfile(ctx context.Context, in *GetTunnelProfileRequest, opts ...grpc.CallOption) (*GetTunnelProfileResponse, error) {
	out := new(GetTunnelProfileResponse)
	err := c.cc.Invoke(ctx, "/daemon.DaemonService/GetTunnelProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) AddTunnelProfile(ctx context.Context, in *TunnelProfileMutationRequest, opts ...grpc.CallOption) (*TunnelProfileMutationResponse, error) {
	out := new(TunnelProfileMutationResponse)
	err := c.cc.Invoke(ctx, "/daemon.DaemonService/AddTunnelProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) UpdateTunnelProfile(ctx context.Context, in *TunnelProfileMutationRequest, opts ...grpc.CallOption) (*TunnelProfileMutationResponse, error) {
	out := new(TunnelProfileMutationResponse)
	err := c.cc.Invoke(ctx, "/daemon.DaemonService/UpdateTunnelProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) DeleteTunnelProfile(ctx context.Context, in *DeleteTunnelProfileRequest, opts ...grpc.CallOption) (*TunnelProfileMutationResponse, error) {
	out := new(TunnelProfileMutationResponse)
	err := c.cc.Invoke(ctx, "/daemon.DaemonService/DeleteTunnelProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DaemonServiceServer is the server API for DaemonService service.
// All implementations must embed UnimplementedDaemonServiceServer
// for forward compatibility
type DaemonServiceServer interface {
	ListConfigurations(context.Context, *ListConfigurationsRequest) (*ListConfigurationsResponse, error)
	ListConfigurationsJSON(context.Context, *ListConfigurationsJSONRequest) (*ListConfigurationsJSONResponse, error)
	AddConfiguration(context.Context, *AddOrUpdateConfigurationRequest) (*AddOrUpdateConfigurationResponse, error)
	AddConfigurationJSON(context.Context, *AddOrUpdateConfigurationRequest) (*MutationResponse, error)
	UpdateConfiguration(context.Context, *AddOrUpdateConfigurationRequest) (*AddOrUpdateConfigurationResponse, error)
	UpdateConfigurationJSON(context.Context, *AddOrUpdateConfigurationRequest) (*MutationResponse, error)
	FetchConfiguration(context.Context, *FetchConfigurationRequest) (*FetchConfigurationResponse, error)
	DeleteConfiguration(context.Context, *DeleteConfigurationRequest) (*DeleteConfigurationResponse, error)
	DeleteConfigurationJSON(context.Context, *DeleteConfigurationRequest) (*MutationResponse, error)
	StartTunnel(context.Context, *StartTunnelRequest) (*StartTunnelResponse, error)
	KillTunnel(context.Context, *KillTunnelRequest) (*KillTunnelResponse, error)
	ListActiveTunnels(context.Context, *ListActiveTunnelsRequest) (*ListActiveTunnelsResponse, error)
	ListActiveTunnelsJSON(context.Context, *ListActiveTunnelsJSONRequest) (*ListActiveTunnelsJSONResponse, error)
	ListMachines(context.Context, *ListMachinesRequest) (*ListMachinesResponse, error)
	GetMachine(context.Context, *GetMachineRequest) (*GetMachineResponse, error)
	AddMachine(context.Context, *MachineMutationRequest) (*MachineMutationResponse, error)
	UpdateMachine(context.Context, *MachineMutationRequest) (*MachineMutationResponse, error)
	DeleteMachine(context.Context, *DeleteMachineRequest) (*MachineMutationResponse, error)
	ListTunnelProfiles(context.Context, *ListTunnelProfilesRequest) (*ListTunnelProfilesResponse, error)
	GetTunnelProfile(context.Context, *GetTunnelProfileRequest) (*GetTunnelProfileResponse, error)
	AddTunnelProfile(context.Context, *TunnelProfileMutationRequest) (*TunnelProfileMutationResponse, error)
	UpdateTunnelProfile(context.Context, *TunnelProfileMutationRequest) (*TunnelProfileMutationResponse, error)
	DeleteTunnelProfile(context.Context, *DeleteTunnelProfileRequest) (*TunnelProfileMutationResponse, error)
	mustEmbedUnimplementedDaemonServiceServer()
}

// UnimplementedDaemonServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDaemonServiceServer struct {
}

func (UnimplementedDaemonServiceServer) ListConfigurations(context.Context, *ListConfigurationsRequest) (*ListConfigurationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListConfigurations not implemented")
}
func (UnimplementedDaemonServiceServer) ListConfigurationsJSON(context.Context, *ListConfigurationsJSONRequest) (*ListConfigurationsJSONResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListConfigurationsJSON not implemented")
}
func (UnimplementedDaemonServiceServer) AddConfiguration(context.Context, *AddOrUpdateConfigurationRequest) (*AddOrUpdateConfigurationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddConfiguration not implemented")
}
func (UnimplementedDaemonServiceServer) AddConfigurationJSON(context.Context, *AddOrUpdateConfigurationRequest) (*MutationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddConfigurationJSON not implemented")
}
func (UnimplementedDaemonServiceServer) UpdateConfiguration(context.Context, *AddOrUpdateConfigurationRequest) (*AddOrUpdateConfigurationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateConfiguration not implemented")
}
func (UnimplementedDaemonServiceServer) UpdateConfigurationJSON(context.Context, *AddOrUpdateConfigurationRequest) (*MutationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateConfigurationJSON not implemented")
}
func (UnimplementedDaemonServiceServer) FetchConfiguration(context.Context, *FetchConfigurationRequest) (*FetchConfigurationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchConfiguration not implemented")
}
func (UnimplementedDaemonServiceServer) DeleteConfiguration(context.Context, *DeleteConfigurationRequest) (*DeleteConfigurationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteConfiguration not implemented")
}
func (UnimplementedDaemonServiceServer) DeleteConfigurationJSON(context.Context, *DeleteConfigurationRequest) (*MutationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteConfigurationJSON not implemented")
}
func (UnimplementedDaemonServiceServer) StartTunnel(context.Context, *StartTunnelRequest) (*StartTunnelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartTunnel not implemented")
}
func (UnimplementedDaemonServiceServer) KillTunnel(context.Context, *KillTunnelRequest) (*KillTunnelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KillTunnel not implemented")
}
func (UnimplementedDaemonServiceServer) ListActiveTunnels(context.Context, *ListActiveTunnelsRequest) (*ListActiveTunnelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListActiveTunnels not implemented")
}
func (UnimplementedDaemonServiceServer) ListActiveTunnelsJSON(context.Context, *ListActiveTunnelsJSONRequest) (*ListActiveTunnelsJSONResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListActiveTunnelsJSON not implemented")
}
func (UnimplementedDaemonServiceServer) ListMachines(context.Context, *ListMachinesRequest) (*ListMachinesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMachines not implemented")
}
func (UnimplementedDaemonServiceServer) GetMachine(context.Context, *GetMachineRequest) (*GetMachineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMachine not implemented")
}
func (UnimplementedDaemonServiceServer) AddMachine(context.Context, *MachineMutationRequest) (*MachineMutationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMachine not implemented")
}
func (UnimplementedDaemonServiceServer) UpdateMachine(context.Context, *MachineMutationRequest) (*MachineMutationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMachine not implemented")
}
func (UnimplementedDaemonServiceServer) DeleteMachine(context.Context, *DeleteMachineRequest) (*MachineMutationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMachine not implemented")
}
func (UnimplementedDaemonServiceServer) ListTunnelProfiles(context.Context, *ListTunnelProfilesRequest) (*ListTunnelProfilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTunnelProfiles not implemented")
}
func (UnimplementedDaemonServiceServer) GetTunnelProfile(context.Context, *GetTunnelProfileRequest) (*GetTunnelProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTunnelProfile not implemented")
}
func (UnimplementedDaemonServiceServer) AddTunnelProfile(context.Context, *TunnelProfileMutationRequest) (*TunnelProfileMutationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTunnelProfile not implemented")
}
func (UnimplementedDaemonServiceServer) UpdateTunnelProfile(context.Context, *TunnelProfileMutationRequest) (*TunnelProfileMutationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTunnelProfile not implemented")
}
func (UnimplementedDaemonServiceServer) DeleteTunnelProfile(context.Context, *DeleteTunnelProfileRequest) (*TunnelProfileMutationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTunnelProfile not implemented")
}
func (UnimplementedDaemonServiceServer) mustEmbedUnimplementedDaemonServiceServer() {}

// UnsafeDaemonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DaemonServiceServer will
// result in compilation errors.
type UnsafeDaemonServiceServer interface {
	mustEmbedUnimplementedDaemonServiceServer()
}

func RegisterDaemonServiceServer(s grpc.ServiceRegistrar, srv DaemonServiceServer) {
	s.RegisterService(&DaemonService_ServiceDesc, srv)
}

func _DaemonService_ListConfigurations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConfigurationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ListConfigurations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daemon.DaemonService/ListConfigurations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ListConfigurations(ctx, req.(*ListConfigurationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ListConfigurationsJSON_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConfigurationsJSONRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ListConfigurationsJSON(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daemon.DaemonService/ListConfigurationsJSON",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ListConfigurationsJSON(ctx, req.(*ListConfigurationsJSONRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_AddConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddOrUpdateConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).AddConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daemon.DaemonService/AddConfiguration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).AddConfiguration(ctx, req.(*AddOrUpdateConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_AddConfigurationJSON_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddOrUpdateConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).AddConfigurationJSON(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daemon.DaemonService/AddConfigurationJSON",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).AddConfigurationJSON(ctx, req.(*AddOrUpdateConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_UpdateConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddOrUpdateConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).UpdateConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daemon.DaemonService/UpdateConfiguration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).UpdateConfiguration(ctx, req.(*AddOrUpdateConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_UpdateConfigurationJSON_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddOrUpdateConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).UpdateConfigurationJSON(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daemon.DaemonService/UpdateConfigurationJSON",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).UpdateConfigurationJSON(ctx, req.(*AddOrUpdateConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_FetchConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).FetchConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daemon.DaemonService/FetchConfiguration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).FetchConfiguration(ctx, req.(*FetchConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_DeleteConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).DeleteConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daemon.DaemonService/DeleteConfiguration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).DeleteConfiguration(ctx, req.(*DeleteConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_DeleteConfigurationJSON_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).DeleteConfigurationJSON(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daemon.DaemonService/DeleteConfigurationJSON",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).DeleteConfigurationJSON(ctx, req.(*DeleteConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_StartTunnel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartTunnelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).StartTunnel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daemon.DaemonService/StartTunnel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).StartTunnel(ctx, req.(*StartTunnelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_KillTunnel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillTunnelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).KillTunnel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daemon.DaemonService/KillTunnel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).KillTunnel(ctx, req.(*KillTunnelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ListActiveTunnels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActiveTunnelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ListActiveTunnels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daemon.DaemonService/ListActiveTunnels",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ListActiveTunnels(ctx, req.(*ListActiveTunnelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ListActiveTunnelsJSON_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActiveTunnelsJSONRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ListActiveTunnelsJSON(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daemon.DaemonService/ListActiveTunnelsJSON",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ListActiveTunnelsJSON(ctx, req.(*ListActiveTunnelsJSONRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ListMachines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMachinesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ListMachines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daemon.DaemonService/ListMachines",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ListMachines(ctx, req.(*ListMachinesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daemon.DaemonService/GetMachine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetMachine(ctx, req.(*GetMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_AddMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MachineMutationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).AddMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daemon.DaemonService/AddMachine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).AddMachine(ctx, req.(*MachineMutationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_UpdateMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MachineMutationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).UpdateMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daemon.DaemonService/UpdateMachine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).UpdateMachine(ctx, req.(*MachineMutationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_DeleteMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).DeleteMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daemon.DaemonService/DeleteMachine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).DeleteMachine(ctx, req.(*DeleteMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ListTunnelProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTunnelProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ListTunnelProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daemon.DaemonService/ListTunnelProfiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ListTunnelProfiles(ctx, req.(*ListTunnelProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetTunnelProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTunnelProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetTunnelProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daemon.DaemonService/GetTunnelProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetTunnelProfile(ctx, req.(*GetTunnelProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_AddTunnelProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TunnelProfileMutationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).AddTunnelProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daemon.DaemonService/AddTunnelProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).AddTunnelProfile(ctx, req.(*TunnelProfileMutationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_UpdateTunnelProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TunnelProfileMutationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).UpdateTunnelProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daemon.DaemonService/UpdateTunnelProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).UpdateTunnelProfile(ctx, req.(*TunnelProfileMutationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_DeleteTunnelProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTunnelProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).DeleteTunnelProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daemon.DaemonService/DeleteTunnelProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).DeleteTunnelProfile(ctx, req.(*DeleteTunnelProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DaemonService_ServiceDesc is the grpc.ServiceDesc for DaemonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DaemonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "daemon.DaemonService",
	HandlerType: (*DaemonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListConfigurations",
			Handler:    _DaemonService_ListConfigurations_Handler,
		},
		{
			MethodName: "ListConfigurationsJSON",
			Handler:    _DaemonService_ListConfigurationsJSON_Handler,
		},
		{
			MethodName: "AddConfiguration",
			Handler:    _DaemonService_AddConfiguration_Handler,
		},
		{
			MethodName: "AddConfigurationJSON",
			Handler:    _DaemonService_AddConfigurationJSON_Handler,
		},
		{
			MethodName: "UpdateConfiguration",
			Handler:    _DaemonService_UpdateConfiguration_Handler,
		},
		{
			MethodName: "UpdateConfigurationJSON",
			Handler:    _DaemonService_UpdateConfigurationJSON_Handler,
		},
		{
			MethodName: "FetchConfiguration",
			Handler:    _DaemonService_FetchConfiguration_Handler,
		},
		{
			MethodName: "DeleteConfiguration",
			Handler:    _DaemonService_DeleteConfiguration_Handler,
		},
		{
			MethodName: "DeleteConfigurationJSON",
			Handler:    _DaemonService_DeleteConfigurationJSON_Handler,
		},
		{
			MethodName: "StartTunnel",
			Handler:    _DaemonService_StartTunnel_Handler,
		},
		{
			MethodName: "KillTunnel",
			Handler:    _DaemonService_KillTunnel_Handler,
		},
		{
			MethodName: "ListActiveTunnels",
			Handler:    _DaemonService_ListActiveTunnels_Handler,
		},
		{
			MethodName: "ListActiveTunnelsJSON",
			Handler:    _DaemonService_ListActiveTunnelsJSON_Handler,
		},
		{
			MethodName: "ListMachines",
			Handler:    _DaemonService_ListMachines_Handler,
		},
		{
			MethodName: "GetMachine",
			Handler:    _DaemonService_GetMachine_Handler,
		},
		{
			MethodName: "AddMachine",
			Handler:    _DaemonService_AddMachine_Handler,
		},
		{
			MethodName: "UpdateMachine",
			Handler:    _DaemonService_UpdateMachine_Handler,
		},
		{
			MethodName: "DeleteMachine",
			Handler:    _DaemonService_DeleteMachine_Handler,
		},
		{
			MethodName: "ListTunnelProfiles",
			Handler:    _DaemonService_ListTunnelProfiles_Handler,
		},
		{
			MethodName: "GetTunnelProfile",
			Handler:    _DaemonService_GetTunnelProfile_Handler,
		},
		{
			MethodName: "AddTunnelProfile",
			Handler:    _DaemonService_AddTunnelProfile_Handler,
		},
		{
			MethodName: "UpdateTunnelProfile",
			Handler:    _DaemonService_UpdateTunnelProfile_Handler,
		},
		{
			MethodName: "DeleteTunnelProfile",
			Handler:    _DaemonService_DeleteTunnelProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/daemon.proto",
}
